name: Automatic build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch: {}

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Deploy
        run: bash tools/deploy.sh
